### ISSUE TITLE
xspdesign.properties date last modified

### ISSUE THREAD

**Issue by paulswithers** [camac/dora#11]
If the xsp.properties file is modified, Git picks up the date last modified in a file xspdesign.properties.

Should this get automatically added to the gitignore by Dora?

**Comment by camac** [comment]
Sounds good to me, there isn't anything else interesting in xspdesign.properties is there?

**Comment by paulswithers** [comment]
Seems to just have the date in it. xsp.properties  holds the actual properties itself
